
spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: buckdestinationet
          group: group
          binder: kafka
        output:
          destination: destination
          group: group
server:
  port: 0
#          binder: kafka